name: Deploy to EKS

on:
  push:
    paths-ignore:
      - "**/az-*.yml"

jobs:
  deploy:
    runs-on: ubuntu-16.04

    # issue with 18.04 https://github.com/dotnet/core/issues/3312

    steps:
    - uses: actions/checkout@master
    
    - name: Login to Docker Hub
      uses: azure/container-actions/docker-login@master
      with:
        login-server: docker.io
        username: {{`${{ secrets.DOCKER_HUB_USERNAME }}`}}
        password: {{`${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}`}}
    
    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push

    - name: Get SQL Server connection string
      id: get-connection-string
      uses: 'docker://sixeyed/actions-rds-get-connection-string:1912'
      env:
        AWS_ACCESS_KEY_ID: {{`${{ secrets.AWS_ACCESS_KEY_ID }}`}}
        AWS_SECRET_ACCESS_KEY: {{`${{ secrets.AWS_SECRET_ACCESS_KEY }}`}}
        AWS_DEFAULT_REGION: {{range .Services}}{{if eq "aws" .ID}}{{.Parameters.region}}{{end}}{{end}}
        SQL_DATABASE_NAME: {{`${{ secrets.RDS_SQL_DATABASE_NAME }}`}}        
        SQL_PASSWORD: {{`${{ secrets.RDS_SQL_PASSWORD }}`}}

    - name: Write Kubernetes secret 
      uses: 'docker://sixeyed/actions-eks-create-secret:1912'
      env:
        AWS_ACCESS_KEY_ID: {{`${{ secrets.AWS_ACCESS_KEY_ID }}`}}
        AWS_SECRET_ACCESS_KEY: {{`${{ secrets.AWS_SECRET_ACCESS_KEY }}`}}
        AWS_DEFAULT_REGION: {{range .Services}}{{if eq "aws" .ID}}{{.Parameters.region}}{{end}}{{end}}
        EKS_CLUSTER_NAME: {{range .Services}}{{if eq "eks" .ID}}{{.Parameters.clusterName}}{{end}}{{end}}
        EKS_SECRET_NAME: db-connection-string
        EKS_SECRET_FILE_NAME: file
        EKS_SECRET_FILE_VALUE: {{`${{ steps.get-connection-string.outputs.connectionString }}`}}
        
    - name: Deploy from Compose to Kubernetes
      uses: 'docker://sixeyed/actions-eks-stack-deploy:1912'
      env:
        AWS_ACCESS_KEY_ID: {{`${{ secrets.AWS_ACCESS_KEY_ID }}`}}
        AWS_SECRET_ACCESS_KEY: {{`${{ secrets.AWS_SECRET_ACCESS_KEY }}`}}
        AWS_DEFAULT_REGION: {{range .Services}}{{if eq "aws" .ID}}{{.Parameters.region}}{{end}}{{end}}
        EKS_CLUSTER_NAME: {{range .Services}}{{if eq "eks" .ID}}{{.Parameters.clusterName}}{{end}}{{end}}
        DOCKER_COMPOSE_PATH: '/github/workspace/docker-compose.production.yaml'
        DOCKER_STACK_NAME: eshoponaws