name: Create RDS database

on: push

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Create SQL Server instamce
      uses: 'docker://sixeyed/actions-rds-create-database:1912'
      env:
        AWS_ACCESS_KEY_ID: {{`${{ secrets.AWS_ACCESS_KEY_ID }}`}}
        AWS_SECRET_ACCESS_KEY: {{`${{ secrets.AWS_SECRET_ACCESS_KEY }}`}}
        AWS_DEFAULT_REGION: {{range .Services}}{{if eq "aws" .ID}}{{.Parameters.region}}{{end}}{{end}}
        SQL_DATABASE_NAME: {{`${{ secrets.RDS_SQL_DATABASE_NAME }}`}}        
        SQL_PASSWORD: {{`${{ secrets.RDS_SQL_PASSWORD }}`}}
    
        